### ISSUE TITLE
Weather Code

### ISSUE THREAD

**Issue by carolinejjones** [metarelate/statistical-process#10]
A metadata encoding for Weather Code.

The weather code is an integer value used to denote different weather types. Each integer code value has an associated meaning.

```
weather_code /(1)              (projection_y_coordinate: 970; projection_x_coordinate: 1042)
Attributes:
	Conventions: CF-1.5
	weather_code: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, ...
        weather_code_meaning: 'Clear_Night Sunny_Day Partly_Cloudy_Night Partly_Cloudy_Day ...'
```

**Comment by marqh** [comment]
hello @carolinejjones 

i think that there is a pattern in the CF conventions that may be used for this

CF defines Flags: flag_values and flag_meanings attributes describe a status flag consisting of mutually exclusive coded values. 
http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#flags

this enables the definition of an enumeration as metadata.

however, these attributes are data variable attributes, so they may have to be defined multiple times

If they are for use on a single data set, they may provide a useful option

**Comment by bayliffe** [comment]
Work completed.
