### ISSUE TITLE
Bounds for integrated quantities

### ISSUE THREAD

**Issue by gavinevans** [metarelate/statistical-process#11]
Quantities that are integrated e.g. https://github.com/metoppv/improver/issues/195 and https://github.com/metoppv/improver/pull/339 currently don't have a convenient way of representing the bounds on an Iris cubes as the bounds would not be monotonic. 

For example when integrating a `height` coordinate downwards, the original height points might be `[5., 10., 20.]`. When integrated downwards, this may be best represented as `[10., 5.]` with bounds of `[10., 20.]` for the point at 10., and bounds of `[5., 20.]` for points at 5., given that the point at 5. includes a contribution for the 10. to 20. layer. 

It's not clear how to indicate the start point of the integration, other than in the upper bound of the highest available point. Is there any alternative way to represent this using sensible metadata?

I think this is related to https://github.com/SciTools/iris/pull/2027.

**Comment by marqh** [comment]
@gavinevans 
If this is due to an Iris constraint on all bounds being monotonic for DimCoords, it could be a functional approach to change the type to AuxCoord, relaxing the bounds constraint whilst keeping the values

**Comment by gavinevans** [comment]
@marqh 
OK. I didn't realise that the requirement for monotonicity wasn't also applied to AuxCoords, so we could take a look at whether that will meet our requirements.
